name: Run Crawler

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install feedparser requests beautifulsoup4

      - run: python crawler.py

      - name: Commit articles.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add articles.json

          git commit -m "Update articles.json" || echo "No changes"

          git push
