name: Run Crawler

on:
  schedule:
    - cron: "0 * * * *"   # Har 1 ghante chalega
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Libraries
        run: |
          pip install feedparser requests beautifulsoup4

      - name: Run Crawler
        run: python crawler.py
